name: Nix

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: hyprwm/actions/.github/workflows/nix.yml@main
    secrets: inherit
    with:
      command: nix flake check -L 'github:${{ github.repository }}?ref=${{ github.ref }}' --extra-substituters "https://hyprland.cachix.org"
